# Generated by Django 2.0.5 on 2019-03-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter your name', max_length=100)),
                ('Area', models.CharField(max_length=100, null=True)),
                ('Total Calls', models.IntegerField(default=0)),
                ('PC', models.IntegerField(default=0)),
                ('Secondary Order Value', models.IntegerField()),
                ('Secondary Collection Value', models.IntegerField()),
                ('Cum Secondary Collection Value', models.IntegerField()),
                ('GT Only', models.IntegerField()),
                ('HA + Promoter Stores', models.IntegerField()),
                ('MT - Stores', models.IntegerField()),
                ('Cumm Collection', models.IntegerField()),
                ('New Stores Today ', models.IntegerField()),
                ('New Stores Comm ', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(help_text='Fill Your Remarks', max_length=4000)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='dataentry',
            name='Town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntryByUser.Town'),
        ),
    ]
