# Generated by Django 2.0.5 on 2019-03-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0002_auto_20190317_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
