# Generated by Django 2.0.5 on 2019-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0003_auto_20190321_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
