# Generated by Django 2.0.5 on 2019-03-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0004_auto_20190321_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
