# Generated by Django 2.0.5 on 2019-03-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0005_auto_20190321_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='EmpId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
