# Generated by Django 2.0.5 on 2019-03-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0006_dataentry_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='date',
            field=models.DateField(),
        ),
    ]
