# Generated by Django 2.0.5 on 2019-03-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0007_auto_20190321_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='Cum Secondary Sales',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
