# Generated by Django 2.0.5 on 2019-03-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0008_dataentry_cum secondary sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='Cum Secondary Collection Value',
            new_name='CumSecondaryCollectionValue',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='Cum Secondary Sales',
            new_name='CumSecondarySales',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='Cumm Collection',
            new_name='CummCollection',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='GT Only',
            new_name='GTOnly',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='HA + Promoter Stores',
            new_name='HA+PromoterStores',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='MT - Stores',
            new_name='MT-Stores',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='New Stores Comm ',
            new_name='NewStoresComm ',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='New Stores Today ',
            new_name='NewStoresToday ',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='Secondary Collection Value',
            new_name='SecondaryCollectionValue',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='Secondary Order Value',
            new_name='SecondaryOrderValue',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='Total Calls',
            new_name='TotalCalls',
        ),
    ]
