# Generated by Django 2.0.5 on 2019-03-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0009_auto_20190321_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='HA+PromoterStores',
            new_name='HAPromoterStores',
        ),
    ]
