# Generated by Django 2.0.5 on 2019-03-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0010_auto_20190321_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='MT-Stores',
            new_name='MTStores',
        ),
    ]
