# Generated by Django 2.0.5 on 2019-03-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0011_auto_20190321_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='NewStoresComm ',
            new_name='NewStoresComm',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='NewStoresToday ',
            new_name='NewStoresToday',
        ),
    ]
