# Generated by Django 2.0.5 on 2019-03-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0012_auto_20190321_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
