# Generated by Django 2.0.5 on 2019-03-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0013_auto_20190322_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='Town',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='Town',
            field=models.ManyToManyField(to='EntryByUser.Town'),
        ),
    ]
