# Generated by Django 2.0.5 on 2019-03-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0014_auto_20190323_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='Town',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='Town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EntryByUser.Town'),
        ),
    ]
