# Generated by Django 2.0.5 on 2019-03-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryByUser', '0015_auto_20190323_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='Town',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
